package com.airline.webservices.rest;


import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@javax.ws.rs.ApplicationPath("webresources")
public class RestApplicationConfig extends Application {

//    @Override
//    public Set<Class<?>> getClasses() {
//        return getRestResourceClasses();
//    }

//    /**
//     * Do not modify this method. It is automatically generated by NetBeans REST support.
//     */
//    private Set<Class<?>> getRestResourceClasses() {
//        Set<Class<?>> resources = new java.util.HashSet<>();
//        resources.add(org.glassfish.movieplex7.MovieSessionBean.class);
//        try {
//            Class<?> jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
//            resources.add(jacksonProvider);
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        return resources;
//    }
    
}